// @created: 2026-03-02
// @updated: 2026-03-02
// @checked: -
/**
 * BreakOverlay - Supplement Tests (onDestroy unlisten)
 *
 * Tests for: frontend/components/BreakOverlay.svelte
 * Generated by: code-to-tests
 *
 * Supplement: L1 gap — onDestroy listener cleanup
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, cleanup } from '@testing-library/svelte';
import BreakOverlay from '@code/frontend/components/BreakOverlay.svelte';

// --- Hoisted mocks ---

const {
  mockClose,
  mockGetTimerState,
  mockOnTimerTick,
  mockOnBreakEnd,
  mockRemainingSecs,
  mockFormatTime,
} = vi.hoisted(() => ({
  mockClose: vi.fn(),
  mockGetTimerState: vi.fn(),
  mockOnTimerTick: vi.fn(),
  mockOnBreakEnd: vi.fn(),
  mockRemainingSecs: vi.fn(),
  mockFormatTime: vi.fn(),
}));

// --- Tauri API mocks ---

vi.mock('@tauri-apps/api/core', () => ({
  invoke: vi.fn(),
}));

vi.mock('@tauri-apps/api/window', () => ({
  getCurrentWindow: vi.fn().mockReturnValue({
    close: mockClose,
  }),
}));

vi.mock('@tauri-apps/api/event', () => ({
  listen: vi.fn().mockResolvedValue(vi.fn()),
}));

// --- timer.ts mock ---

vi.mock('@code/frontend/lib/timer', () => ({
  remainingSecs: mockRemainingSecs,
  formatTime: mockFormatTime,
  getTimerState: mockGetTimerState,
  pauseTimer: vi.fn(),
  resumeTimer: vi.fn(),
  togglePause: vi.fn(),
  skipBreak: vi.fn(),
  updateSettings: vi.fn(),
  closeBreakOverlay: vi.fn(),
  quitApp: vi.fn(),
  onTimerTick: mockOnTimerTick,
  onPhaseChanged: vi.fn().mockResolvedValue(vi.fn()),
  onBreakStart: vi.fn().mockResolvedValue(vi.fn()),
  onBreakEnd: mockOnBreakEnd,
}));

// --- settings-store mock ---

vi.mock('@code/frontend/lib/settings-store', () => ({
  loadSettings: vi.fn(),
  saveSettings: vi.fn(),
  toTimerSettings: vi.fn(),
  toDisplaySettings: vi.fn(),
}));

// --- Helpers ---

function makeTimerState(overrides: Record<string, unknown> = {}) {
  return {
    phase: 'ShortBreak',
    paused: false,
    elapsed_secs: 0,
    phase_duration_secs: 20,
    short_break_count: 1,
    settings: {
      focus_duration_secs: 1200,
      short_break_duration_secs: 20,
      long_break_duration_secs: 180,
      short_breaks_before_long: 3,
    },
    ...overrides,
  };
}

// --- Tests ---

describe('BreakOverlay - onDestroy cleanup', () => {
  let mockUnlistenTick: ReturnType<typeof vi.fn>;
  let mockUnlistenEnd: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    vi.clearAllMocks();
    mockRemainingSecs.mockReturnValue(20);
    mockFormatTime.mockReturnValue('00:20');
    mockGetTimerState.mockResolvedValue(makeTimerState());

    // Create trackable unlisten functions for each render
    mockUnlistenTick = vi.fn();
    mockUnlistenEnd = vi.fn();
    mockOnTimerTick.mockResolvedValue(mockUnlistenTick);
    mockOnBreakEnd.mockResolvedValue(mockUnlistenEnd);
  });

  afterEach(() => { cleanup(); });

  it('unlistenTick and unlistenEnd are called on unmount', async () => {
    // Trace: onMount → getTimerState() → handleTick(state)
    //   → onTimerTick(handleTick) resolves to mockUnlistenTick → stored in unlistenTick
    //   → onBreakEnd(handleBreakEnd) resolves to mockUnlistenEnd → stored in unlistenEnd
    // onDestroy → unlistenTick?.() → mockUnlistenTick called
    //           → unlistenEnd?.() → mockUnlistenEnd called
    const { unmount } = render(BreakOverlay);

    // Wait for onMount async to complete (listeners registered)
    await vi.waitFor(() => {
      expect(mockOnTimerTick).toHaveBeenCalledTimes(1);
      expect(mockOnBreakEnd).toHaveBeenCalledTimes(1);
    });

    // Unmount triggers onDestroy
    unmount();

    expect(mockUnlistenTick).toHaveBeenCalledTimes(1);
    expect(mockUnlistenEnd).toHaveBeenCalledTimes(1);
  });

  it('unlisten is not called when unmounted before onMount completes (null safety)', async () => {
    // Trace: onMount starts but getTimerState never resolves
    //   → unlistenTick remains null, unlistenEnd remains null
    // onDestroy → unlistenTick?.() → no-op (null)
    //           → unlistenEnd?.() → no-op (null)
    mockGetTimerState.mockReturnValue(new Promise(() => {})); // never resolves

    const { unmount } = render(BreakOverlay);

    // onTimerTick/onBreakEnd should NOT have been called yet
    // (they are called after getTimerState resolves)
    expect(mockOnTimerTick).not.toHaveBeenCalled();
    expect(mockOnBreakEnd).not.toHaveBeenCalled();

    // Unmount before onMount completes — should not throw
    unmount();

    // unlisten functions were never set, so they should not be called
    expect(mockUnlistenTick).not.toHaveBeenCalled();
    expect(mockUnlistenEnd).not.toHaveBeenCalled();
  });
});
