// meta: updated=2026-03-11 06:10 checked=-
// Supplement: L1/L2 gaps from code-to-tests
/**
 * TrayPanel - Supplement Tests
 *
 * Tests for: code/frontend/components/TrayPanel.svelte
 * Spec: _documents/spec/frontend/components/tray-panel.md
 * Generated by: code-to-tests
 *
 * L1: handleTogglePause — not tested
 * L2: loadSavedSettings (saved !== null) — non-null branch untested
 * L2: handleTick via onTimerTick callback — callback-based update unverified
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, cleanup } from '@testing-library/svelte';
import type { TimerState } from '@code/frontend/lib/timer';
import TrayPanel from '@code/frontend/components/TrayPanel.svelte';

afterEach(() => { cleanup(); });

// --- Tauri API mocks ---

vi.mock('@tauri-apps/api/core', () => ({
  invoke: vi.fn(),
}));

vi.mock('@tauri-apps/api/event', () => ({
  listen: vi.fn().mockResolvedValue(vi.fn()),
  emit: vi.fn().mockResolvedValue(undefined),
  emitTo: vi.fn().mockResolvedValue(undefined),
}));

vi.mock('@tauri-apps/api/window', () => ({
  getCurrentWindow: vi.fn().mockReturnValue({
    close: vi.fn(),
    setSize: vi.fn().mockResolvedValue(undefined),
  }),
}));

// --- timer.ts mock ---

const {
  mockGetTimerState,
  mockTogglePause,
  mockUpdateSettings,
  mockQuitApp,
  mockOnTimerTick,
  mockRemainingSecs,
  mockFormatTime,
} = vi.hoisted(() => ({
  mockGetTimerState: vi.fn(),
  mockTogglePause: vi.fn(),
  mockUpdateSettings: vi.fn(),
  mockQuitApp: vi.fn(),
  mockOnTimerTick: vi.fn().mockResolvedValue(vi.fn()),
  mockRemainingSecs: vi.fn(),
  mockFormatTime: vi.fn(),
}));

vi.mock('@code/frontend/lib/timer', () => ({
  remainingSecs: mockRemainingSecs,
  formatTime: mockFormatTime,
  getTimerState: mockGetTimerState,
  pauseTimer: vi.fn(),
  resumeTimer: vi.fn(),
  togglePause: mockTogglePause,
  skipBreak: vi.fn(),
  updateSettings: mockUpdateSettings,
  resetTimer: vi.fn(),
  closeBreakOverlay: vi.fn(),
  quitApp: mockQuitApp,
  onTimerTick: mockOnTimerTick,
  onPhaseChanged: vi.fn().mockResolvedValue(vi.fn()),
  onBreakStart: vi.fn().mockResolvedValue(vi.fn()),
  onBreakEnd: vi.fn().mockResolvedValue(vi.fn()),
  getTodaySessions: vi.fn().mockResolvedValue(0),
  acceptBreak: vi.fn(),
  extendFocus: vi.fn(),
  skipBreakFromFocus: vi.fn(),
  setTrayIconVisible: vi.fn().mockResolvedValue(undefined),
  listCassettes: vi.fn().mockResolvedValue([]),
  switchCassette: vi.fn().mockResolvedValue(undefined),
  openCassetteFolder: vi.fn().mockResolvedValue(undefined),
}));

vi.mock('@tauri-apps/plugin-autostart', () => ({
  isEnabled: vi.fn().mockResolvedValue(false),
  enable: vi.fn().mockResolvedValue(undefined),
  disable: vi.fn().mockResolvedValue(undefined),
}));

// --- settings-store mock ---

const {
  mockLoadSettings,
  mockSaveSettings,
  mockToTimerSettings,
  mockToDisplaySettings,
} = vi.hoisted(() => ({
  mockLoadSettings: vi.fn(),
  mockSaveSettings: vi.fn(),
  mockToTimerSettings: vi.fn(),
  mockToDisplaySettings: vi.fn(),
}));

vi.mock('@code/frontend/lib/settings-store', () => ({
  loadSettings: mockLoadSettings,
  saveSettings: mockSaveSettings,
  toTimerSettings: mockToTimerSettings,
  toDisplaySettings: mockToDisplaySettings,
  loadPauseMediaOnBreak: vi.fn().mockResolvedValue(false),
  savePauseMediaOnBreak: vi.fn().mockResolvedValue(undefined),
  loadHideTrayIcon: vi.fn().mockResolvedValue(false),
  saveHideTrayIcon: vi.fn().mockResolvedValue(undefined),
  loadTickVolume: vi.fn().mockResolvedValue(0),
  saveTickVolume: vi.fn().mockResolvedValue(undefined),
  loadPresenceToast: vi.fn().mockResolvedValue(true),
  savePresenceToast: vi.fn().mockResolvedValue(undefined),
  loadPresencePosition: vi.fn().mockResolvedValue('top-right'),
  savePresencePosition: vi.fn().mockResolvedValue(undefined),
  loadPresenceLevel: vi.fn().mockResolvedValue('front'),
  savePresenceLevel: vi.fn().mockResolvedValue(undefined),
  loadPresenceMaxToasts: vi.fn().mockResolvedValue(4),
  savePresenceMaxToasts: vi.fn().mockResolvedValue(undefined),
  loadPresenceShowIcon: vi.fn().mockResolvedValue(true),
  savePresenceShowIcon: vi.fn().mockResolvedValue(undefined),
  loadPresenceLikeIcon: vi.fn().mockResolvedValue('heart'),
  savePresenceLikeIcon: vi.fn().mockResolvedValue(undefined),
  loadLocale: vi.fn().mockResolvedValue(null),
  saveLocale: vi.fn().mockResolvedValue(undefined),
}));

// --- Helpers ---

function makeTimerState(overrides: Partial<TimerState> = {}): TimerState {
  return {
    phase: 'Focus',
    paused: false,
    elapsed_secs: 0,
    phase_duration_secs: 1200,
    short_break_count: 0,
    settings: {
      focus_duration_secs: 1200,
      short_break_duration_secs: 20,
      long_break_duration_secs: 180,
      short_breaks_before_long: 3,
    },
    ...overrides,
  };
}

// --- Tests ---

describe('TrayPanel - supplement', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockRemainingSecs.mockReturnValue(1200);
    mockFormatTime.mockReturnValue('20:00');
    mockGetTimerState.mockResolvedValue(makeTimerState());
    mockLoadSettings.mockResolvedValue(null);
    mockTogglePause.mockResolvedValue(true);
    mockToTimerSettings.mockReturnValue({
      focus_duration_secs: 1200,
      short_break_duration_secs: 20,
      long_break_duration_secs: 180,
      short_breaks_before_long: 3,
    });
  });

  // =========================================================================
  // L1: handleTogglePause
  // =========================================================================
  // Code trace (TrayPanel.svelte L48-50):
  //   async function handleTogglePause() {
  //     paused = await togglePause();
  //   }
  // togglePause returns a boolean. The return value is assigned to `paused`.
  // `paused` controls TimerControls button text: true -> "▶ Resume", false -> "⏸ Pause"

  describe('handleTogglePause (L1)', () => {
    it('clicking toggle button calls togglePause', async () => {
      // Initial state: paused=false -> button shows "⏸ Pause"
      mockTogglePause.mockResolvedValue(true);

      render(TrayPanel);

      await vi.waitFor(() => {
        expect(mockGetTimerState).toHaveBeenCalled();
      });

      const pauseButton = screen.getByText('⏸ Pause');
      await fireEvent.click(pauseButton);

      await vi.waitFor(() => {
        expect(mockTogglePause).toHaveBeenCalledTimes(1);
      });
    });

    it('shows "▶ Resume" when togglePause returns true', async () => {
      // Code trace:
      //   handleTogglePause -> paused = await togglePause()
      //   togglePause returns true -> paused becomes true
      //   TimerControls receives paused=true -> shows "▶ Resume"
      mockTogglePause.mockResolvedValue(true);

      render(TrayPanel);

      await vi.waitFor(() => {
        expect(mockGetTimerState).toHaveBeenCalled();
      });

      const pauseButton = screen.getByText('⏸ Pause');
      await fireEvent.click(pauseButton);

      await vi.waitFor(() => {
        expect(screen.getByText('▶ Resume')).toBeTruthy();
      });
    });

    it('keeps "⏸ Pause" when togglePause returns false', async () => {
      // Code trace:
      //   handleTogglePause -> paused = await togglePause()
      //   togglePause returns false -> paused becomes false
      //   TimerControls receives paused=false -> shows "⏸ Pause"
      mockTogglePause.mockResolvedValue(false);

      render(TrayPanel);

      await vi.waitFor(() => {
        expect(mockGetTimerState).toHaveBeenCalled();
      });

      const pauseButton = screen.getByText('⏸ Pause');
      await fireEvent.click(pauseButton);

      await vi.waitFor(() => {
        expect(mockTogglePause).toHaveBeenCalledTimes(1);
        expect(screen.getByText('⏸ Pause')).toBeTruthy();
      });
    });
  });

  // =========================================================================
  // L2: loadSavedSettings (saved !== null)
  // =========================================================================
  // Code trace (TrayPanel.svelte L58-67):
  //   async function loadSavedSettings() {
  //     const saved = await loadSettings();
  //     if (saved) {
  //       focusMinutes = saved.focusMinutes;                    // L61
  //       shortBreakMinutes = saved.shortBreakMinutes;          // L62
  //       longBreakMinutes = saved.longBreakMinutes;            // L63
  //       shortBreaksBeforeLong = saved.shortBreaksBeforeLong;  // L64
  //       await updateSettings(toTimerSettings(saved));         // L65
  //     }
  //   }
  // When saved !== null: state variables are updated, then
  // toTimerSettings(saved) is called, result passed to updateSettings.

  describe('loadSavedSettings with non-null settings (L2)', () => {
    it('toTimerSettings and updateSettings are called when saved settings exist', async () => {
      const savedSettings = {
        focusMinutes: 30,
        shortBreakMinutes: 2,
        longBreakMinutes: 5,
        shortBreaksBeforeLong: 4,
      };
      mockLoadSettings.mockResolvedValue(savedSettings);
      const convertedSettings = {
        focus_duration_secs: 1800,
        short_break_duration_secs: 120,
        long_break_duration_secs: 300,
        short_breaks_before_long: 4,
      };
      mockToTimerSettings.mockReturnValue(convertedSettings);

      render(TrayPanel);

      // Code trace:
      //   loadSavedSettings() → saved = { focusMinutes:30, ... }
      //   saved !== null → enters if block
      //   L65: toTimerSettings(saved) → convertedSettings
      //   L65: updateSettings(convertedSettings)
      await vi.waitFor(() => {
        expect(mockToTimerSettings).toHaveBeenCalledWith(savedSettings);
        expect(mockUpdateSettings).toHaveBeenCalledWith(convertedSettings);
      });
    });

    it('saved settings values are reflected in SettingsForm', async () => {
      const savedSettings = {
        focusMinutes: 30,
        shortBreakMinutes: 3,
        longBreakMinutes: 10,
        shortBreaksBeforeLong: 5,
      };
      mockLoadSettings.mockResolvedValue(savedSettings);

      render(TrayPanel);

      // Code trace:
      //   loadSavedSettings() → saved = { focusMinutes:30, shortBreakMinutes:3, ... }
      //   L61-64: focusMinutes=30, shortBreakMinutes=3, longBreakMinutes=10, shortBreaksBeforeLong=5
      //   These are bound to SettingsForm inputs via bind:value
      await vi.waitFor(() => {
        const focusInput = document.getElementById('focus') as HTMLInputElement;
        expect(focusInput).toBeTruthy();
        // Svelte binds the value; check the DOM input value
        expect(focusInput.value).toBe('30');

        const shortBreakInput = document.getElementById('short-break') as HTMLInputElement;
        expect(shortBreakInput.value).toBe('3');

        const longBreakInput = document.getElementById('long-break') as HTMLInputElement;
        expect(longBreakInput.value).toBe('10');

        const cyclesInput = document.getElementById('cycles') as HTMLInputElement;
        expect(cyclesInput.value).toBe('5');
      });
    });
  });

  // =========================================================================
  // L2: handleTick via onTimerTick callback
  // =========================================================================
  // Code trace (TrayPanel.svelte L41-46):
  //   function handleTick(state: TimerState) {
  //     timerState = state;
  //     remaining = formatTime(remainingSecs(state));  // L43
  //     phaseLabel = phaseLabels[state.phase] || state.phase; // L44
  //     paused = state.paused;                          // L45
  //   }
  // onMount subscribes handleTick to onTimerTick. When a tick event arrives,
  // handleTick updates remaining, phaseLabel, and paused.

  describe('handleTick via onTimerTick callback (L2)', () => {
    it('remaining is updated via onTimerTick callback', async () => {
      render(TrayPanel);

      await vi.waitFor(() => {
        expect(mockOnTimerTick).toHaveBeenCalledTimes(1);
      });

      const handleTick = mockOnTimerTick.mock.calls[0][0];

      mockRemainingSecs.mockReturnValue(15);
      mockFormatTime.mockReturnValue('00:15');
      handleTick(makeTimerState({ phase: 'ShortBreak', elapsed_secs: 5, phase_duration_secs: 20 }));

      await vi.waitFor(() => {
        expect(screen.getByText('00:15')).toBeTruthy();
      });
    });

    it('paused state is reflected via onTimerTick callback', async () => {
      render(TrayPanel);

      await vi.waitFor(() => {
        expect(mockOnTimerTick).toHaveBeenCalledTimes(1);
      });

      const handleTick = mockOnTimerTick.mock.calls[0][0];

      mockRemainingSecs.mockReturnValue(1100);
      mockFormatTime.mockReturnValue('18:20');
      handleTick(makeTimerState({ phase: 'Focus', paused: true, elapsed_secs: 100 }));

      await vi.waitFor(() => {
        expect(screen.getByText('▶ Resume')).toBeTruthy();
      });
    });
  });
});
