// Supplement: L1/L2 gaps from code-to-tests
// @created: 2026-02-26
// @updated: 2026-02-26
// @checked: -
/**
 * TrayPanel - Supplement Tests
 *
 * Tests for: code/frontend/components/TrayPanel.svelte
 * Spec: documents/spec/frontend/components/tray-panel.md
 * Generated by: code-to-tests
 *
 * L1: handleTogglePause — テストなし
 * L2: loadSavedSettings (saved !== null) — 非null分岐が未テスト
 * L2: handleTick via onTimerTick callback — コールバック経由の更新が未検証
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, cleanup } from '@testing-library/svelte';
import TrayPanel from '../../../../code/frontend/components/TrayPanel.svelte';

afterEach(() => { cleanup(); });

// --- Tauri API mocks ---

vi.mock('@tauri-apps/api/core', () => ({
  invoke: vi.fn(),
}));

vi.mock('@tauri-apps/api/event', () => ({
  listen: vi.fn().mockResolvedValue(vi.fn()),
}));

vi.mock('@tauri-apps/api/window', () => ({
  getCurrentWindow: vi.fn().mockReturnValue({
    close: vi.fn(),
  }),
}));

// --- timer.ts mock ---

const mockGetTimerState = vi.fn();
const mockTogglePause = vi.fn();
const mockUpdateSettings = vi.fn();
const mockQuitApp = vi.fn();
const mockOnTimerTick = vi.fn().mockResolvedValue(vi.fn());
const mockRemainingSecs = vi.fn();
const mockFormatTime = vi.fn();

vi.mock('../../../../code/frontend/lib/timer', () => ({
  remainingSecs: (...args: unknown[]) => mockRemainingSecs(...args),
  formatTime: (...args: unknown[]) => mockFormatTime(...args),
  getTimerState: (...args: unknown[]) => mockGetTimerState(...args),
  pauseTimer: vi.fn(),
  resumeTimer: vi.fn(),
  togglePause: (...args: unknown[]) => mockTogglePause(...args),
  skipBreak: vi.fn(),
  updateSettings: (...args: unknown[]) => mockUpdateSettings(...args),
  closeBreakOverlay: vi.fn(),
  quitApp: (...args: unknown[]) => mockQuitApp(...args),
  onTimerTick: (...args: unknown[]) => mockOnTimerTick(...args),
  onPhaseChanged: vi.fn().mockResolvedValue(vi.fn()),
  onBreakStart: vi.fn().mockResolvedValue(vi.fn()),
  onBreakEnd: vi.fn().mockResolvedValue(vi.fn()),
}));

// --- settings-store mock ---

const mockLoadSettings = vi.fn();
const mockSaveSettings = vi.fn();
const mockToTimerSettings = vi.fn();
const mockToDisplaySettings = vi.fn();

vi.mock('../../../../code/frontend/lib/settings-store', () => ({
  loadSettings: (...args: unknown[]) => mockLoadSettings(...args),
  saveSettings: (...args: unknown[]) => mockSaveSettings(...args),
  toTimerSettings: (...args: unknown[]) => mockToTimerSettings(...args),
  toDisplaySettings: (...args: unknown[]) => mockToDisplaySettings(...args),
}));

// --- Helpers ---

function makeTimerState(overrides: Record<string, unknown> = {}) {
  return {
    phase: 'Focus',
    paused: false,
    elapsed_secs: 0,
    phase_duration_secs: 1200,
    short_break_count: 0,
    settings: {
      focus_duration_secs: 1200,
      short_break_duration_secs: 20,
      long_break_duration_secs: 180,
      short_breaks_before_long: 3,
    },
    ...overrides,
  };
}

// --- Tests ---

describe('TrayPanel - supplement', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockRemainingSecs.mockReturnValue(1200);
    mockFormatTime.mockReturnValue('20:00');
    mockGetTimerState.mockResolvedValue(makeTimerState());
    mockLoadSettings.mockResolvedValue(null);
    mockTogglePause.mockResolvedValue(true);
    mockToTimerSettings.mockReturnValue({
      focus_duration_secs: 1200,
      short_break_duration_secs: 20,
      long_break_duration_secs: 180,
      short_breaks_before_long: 3,
    });
  });

  // =========================================================================
  // L1: handleTogglePause
  // =========================================================================
  // Code trace (TrayPanel.svelte L48-50):
  //   async function handleTogglePause() {
  //     paused = await togglePause();
  //   }
  // togglePause returns a boolean. The return value is assigned to `paused`.
  // `paused` controls TimerControls button text: true → "▶ 再開", false → "⏸ 一時停止"

  describe('handleTogglePause (L1)', () => {
    it('トグルボタンクリックで togglePause が呼ばれる', async () => {
      // Initial state: paused=false → button shows "⏸ 一時停止"
      mockTogglePause.mockResolvedValue(true);

      render(TrayPanel);

      await vi.waitFor(() => {
        expect(mockGetTimerState).toHaveBeenCalled();
      });

      const pauseButton = screen.getByText('⏸ 一時停止');
      await fireEvent.click(pauseButton);

      await vi.waitFor(() => {
        expect(mockTogglePause).toHaveBeenCalledTimes(1);
      });
    });

    it('togglePause が true を返すと "▶ 再開" が表示される', async () => {
      // Code trace:
      //   handleTogglePause → paused = await togglePause()
      //   togglePause returns true → paused becomes true
      //   TimerControls receives paused=true → shows "▶ 再開"
      mockTogglePause.mockResolvedValue(true);

      render(TrayPanel);

      await vi.waitFor(() => {
        expect(mockGetTimerState).toHaveBeenCalled();
      });

      const pauseButton = screen.getByText('⏸ 一時停止');
      await fireEvent.click(pauseButton);

      await vi.waitFor(() => {
        expect(screen.getByText('▶ 再開')).toBeTruthy();
      });
    });

    it('togglePause が false を返すと "⏸ 一時停止" が維持される', async () => {
      // Code trace:
      //   handleTogglePause → paused = await togglePause()
      //   togglePause returns false → paused becomes false
      //   TimerControls receives paused=false → shows "⏸ 一時停止"
      mockTogglePause.mockResolvedValue(false);

      render(TrayPanel);

      await vi.waitFor(() => {
        expect(mockGetTimerState).toHaveBeenCalled();
      });

      const pauseButton = screen.getByText('⏸ 一時停止');
      await fireEvent.click(pauseButton);

      await vi.waitFor(() => {
        expect(mockTogglePause).toHaveBeenCalledTimes(1);
        expect(screen.getByText('⏸ 一時停止')).toBeTruthy();
      });
    });
  });

  // =========================================================================
  // L2: loadSavedSettings (saved !== null)
  // =========================================================================
  // Code trace (TrayPanel.svelte L58-67):
  //   async function loadSavedSettings() {
  //     const saved = await loadSettings();
  //     if (saved) {
  //       focusMinutes = saved.focusMinutes;           // L61
  //       shortBreakSecs = saved.shortBreakSecs;       // L62
  //       longBreakMinutes = saved.longBreakMinutes;    // L63
  //       shortBreaksBeforeLong = saved.shortBreaksBeforeLong; // L64
  //       await updateSettings(toTimerSettings(saved)); // L65
  //     }
  //   }
  // When saved !== null: state variables are updated, then
  // toTimerSettings(saved) is called, result passed to updateSettings.

  describe('loadSavedSettings with non-null settings (L2)', () => {
    it('保存済み設定が存在する場合 toTimerSettings → updateSettings が呼ばれる', async () => {
      const savedSettings = {
        focusMinutes: 30,
        shortBreakSecs: 30,
        longBreakMinutes: 5,
        shortBreaksBeforeLong: 4,
      };
      mockLoadSettings.mockResolvedValue(savedSettings);
      const convertedSettings = {
        focus_duration_secs: 1800,
        short_break_duration_secs: 30,
        long_break_duration_secs: 300,
        short_breaks_before_long: 4,
      };
      mockToTimerSettings.mockReturnValue(convertedSettings);

      render(TrayPanel);

      // Code trace:
      //   loadSavedSettings() → saved = { focusMinutes:30, ... }
      //   saved !== null → enters if block
      //   L65: toTimerSettings(saved) → convertedSettings
      //   L65: updateSettings(convertedSettings)
      await vi.waitFor(() => {
        expect(mockToTimerSettings).toHaveBeenCalledWith(savedSettings);
        expect(mockUpdateSettings).toHaveBeenCalledWith(convertedSettings);
      });
    });

    it('保存済み設定の値が SettingsForm に反映される', async () => {
      const savedSettings = {
        focusMinutes: 30,
        shortBreakSecs: 45,
        longBreakMinutes: 10,
        shortBreaksBeforeLong: 5,
      };
      mockLoadSettings.mockResolvedValue(savedSettings);

      render(TrayPanel);

      // Code trace:
      //   loadSavedSettings() → saved = { focusMinutes:30, shortBreakSecs:45, ... }
      //   L61-64: focusMinutes=30, shortBreakSecs=45, longBreakMinutes=10, shortBreaksBeforeLong=5
      //   These are bound to SettingsForm inputs via bind:value
      await vi.waitFor(() => {
        const focusInput = document.getElementById('focus') as HTMLInputElement;
        expect(focusInput).toBeTruthy();
        // Svelte binds the value; check the DOM input value
        expect(focusInput.value).toBe('30');

        const shortBreakInput = document.getElementById('short-break') as HTMLInputElement;
        expect(shortBreakInput.value).toBe('45');

        const longBreakInput = document.getElementById('long-break') as HTMLInputElement;
        expect(longBreakInput.value).toBe('10');

        const cyclesInput = document.getElementById('cycles') as HTMLInputElement;
        expect(cyclesInput.value).toBe('5');
      });
    });
  });

  // =========================================================================
  // L2: handleTick via onTimerTick callback
  // =========================================================================
  // Code trace (TrayPanel.svelte L41-46):
  //   function handleTick(state: TimerState) {
  //     timerState = state;
  //     remaining = formatTime(remainingSecs(state));  // L43
  //     phaseLabel = phaseLabels[state.phase] || state.phase; // L44
  //     paused = state.paused;                          // L45
  //   }
  // onMount subscribes handleTick to onTimerTick. When a tick event arrives,
  // handleTick updates remaining, phaseLabel, and paused.

  describe('handleTick via onTimerTick callback (L2)', () => {
    it('onTimerTick コールバック経由で remaining と phaseLabel が更新される', async () => {
      render(TrayPanel);

      await vi.waitFor(() => {
        expect(mockOnTimerTick).toHaveBeenCalledTimes(1);
      });

      // Retrieve the handleTick callback registered with onTimerTick
      const handleTick = mockOnTimerTick.mock.calls[0][0];

      // Simulate a tick with ShortBreak phase
      // Code trace:
      //   handleTick({ phase:'ShortBreak', paused:false, elapsed_secs:5, ... })
      //   L43: remaining = formatTime(remainingSecs(state))
      //     mockRemainingSecs returns 15, mockFormatTime returns '00:15'
      //   L44: phaseLabel = phaseLabels['ShortBreak'] = '短い休憩中'
      //   L45: paused = false
      mockRemainingSecs.mockReturnValue(15);
      mockFormatTime.mockReturnValue('00:15');
      handleTick(makeTimerState({ phase: 'ShortBreak', elapsed_secs: 5, phase_duration_secs: 20 }));

      await vi.waitFor(() => {
        expect(screen.getByText('短い休憩中')).toBeTruthy();
        expect(screen.getByText('00:15')).toBeTruthy();
      });
    });

    it('onTimerTick コールバックで paused 状態が反映される', async () => {
      render(TrayPanel);

      await vi.waitFor(() => {
        expect(mockOnTimerTick).toHaveBeenCalledTimes(1);
      });

      const handleTick = mockOnTimerTick.mock.calls[0][0];

      // Simulate a tick where paused=true
      // Code trace:
      //   handleTick({ phase:'Focus', paused:true, ... })
      //   L45: paused = true
      //   TimerControls receives paused=true → "▶ 再開"
      //   TimerStatus receives paused=true → "一時停止中" badge
      mockRemainingSecs.mockReturnValue(1100);
      mockFormatTime.mockReturnValue('18:20');
      handleTick(makeTimerState({ phase: 'Focus', paused: true, elapsed_secs: 100 }));

      await vi.waitFor(() => {
        expect(screen.getByText('▶ 再開')).toBeTruthy();
        expect(screen.getByText('一時停止中')).toBeTruthy();
      });
    });
  });
});
